
import httpx
# import pandas as pd # Lazy Import
# import yfinance as yf # Lazy Import
import gc
from datetime import datetime, timedelta
from typing import Optional, Dict, List, Any, Callable
from pathlib import Path
import os

from app.database import get_db
from app.config import STOCK_NAME_CACHE, SUPPLEMENTARY_NAME_CACHE
from app.services.market_db import get_connection

def load_stock_name_cache():
    """Load stock names from Mars Strategy Excel file into global cache."""
    import pandas as pd
    # Load from CSV (Generated by StockInfoService)
    try:
        # 1. Try relative to this file (for deployed app)
        base_dir = Path(__file__).parent.parent # app/
        # Try finding the CSV file in standard locations
        csv_path = base_dir / "project_tw/stock_list.csv"
        
        if not csv_path.exists():
            # Dev environment fallback
            csv_path = base_dir.parent / "app/project_tw/stock_list.csv"
            
        if not csv_path.exists():
             # Last resort: Try root
             csv_path = Path("/app/app/project_tw/stock_list.csv")

        if csv_path.exists():
            print(f"[Cache] Loading stock names from {csv_path}")
            # CSV columns: code, name, industry, market_type
            df = pd.read_csv(csv_path, dtype={'code': str, 'name': str})
            
            # Create dict: code -> name
            if 'code' in df.columns and 'name' in df.columns:
                new_cache = dict(zip(df['code'], df['name']))
                STOCK_NAME_CACHE.update(new_cache)
                print(f"[Cache] Loaded {len(new_cache)} stock names")
            else:
                print(f"[Cache Warning] Columns 'code'/'name' not found in {csv_path}")
                
            # Merge Manual Map
            STOCK_NAME_CACHE.update(SUPPLEMENTARY_NAME_CACHE)
        else:
             print(f"[Cache Warning] Stock list CSV not found at {csv_path}")
             
    except Exception as e:
        print(f"[Cache Error] Failed to load stock list CSV: {e}")

    # Merge Supplementary Cache (Overrides Excel if collision, or adds new) - Already done above
    if SUPPLEMENTARY_NAME_CACHE:
        # print(f"[Cache] Merging {len(SUPPLEMENTARY_NAME_CACHE)} supplementary names")
        STOCK_NAME_CACHE.update(SUPPLEMENTARY_NAME_CACHE)

def fetch_chinese_name_from_api(stock_id: str) -> Optional[str]:
    """
    Fetch Chinese name from TWSE/TPEx official APIs.
    Fallback logic for missing names.
    """
    try:
        today = datetime.now()
        # TWSE/TPEx data usually available after 1:30 PM.
        # but usually using a known recent date or just 'latest' if API supports
        # TWSE needs specific date. Let's use yesterday.
        offset = 1
        if today.weekday() == 0:
            offset = 3 # Monday -> Friday
        elif today.weekday() == 6:
            offset = 2 # Sunday -> Friday
        
        date_obj = today - timedelta(days=offset)
        date_str = date_obj.strftime("%Y%m%d")
        
        # Try TWSE first (covers most stocks)
        try:
            url = "https://www.twse.com.tw/exchangeReport/MI_INDEX"
            params = {"response": "json", "type": "ALLBUT0999", "date": date_str}
            
            # fast timeout
            with httpx.Client(verify=False, timeout=5.0) as client:
                resp = client.get(url, params=params)
                data = resp.json()
                
                if data.get('stat') == 'OK':
                    tables = data.get('tables', [])
                    # Usually table 9 is the main price table with Code/Name
                    for table in tables:
                        fields = table.get('fields', [])
                        if '證券代號' in fields and '證券名稱' in fields:
                            idx_code = fields.index('證券代號')
                            idx_name = fields.index('證券名稱')
                            
                            for row in table.get('data', []):
                                if row[idx_code] == stock_id:
                                    return row[idx_name]
        except Exception as e:
            print(f"[API] TWSE fetch error: {e}")
        
        # Try TPEx (OTC stocks)
        try:
            # TPEx needs ROC year: 2024 -> 113
            roc_year = date_obj.year - 1911
            roc_date = f"{roc_year}/{date_obj.month:02d}/{date_obj.day:02d}"
            
            url = "https://www.tpex.org.tw/web/stock/aftertrading/daily_close_quotes/stk_quote_result.php"
            params = {"l": "zh-tw", "d": roc_date, "se": "AL"}  # AL = All securities
            
            with httpx.Client(timeout=5.0) as client:
                resp = client.get(url, params=params)
                data = resp.json()
                
                if 'aaData' in data:
                    for row in data['aaData']:
                        # Row format: [Code, Name, ...]
                        if row[0] == stock_id:
                            return row[1]
        except Exception as e:
            print(f"[API] TPEx fetch error: {e}")
            
    except Exception as e:
        print(f"[API] Error fetching name for {stock_id}: {e}")
    
    return None

def fetch_stock_name(stock_id: str) -> Optional[str]:
    import yfinance as yf
    """
    Fetch stock name.
    Priority:
    1. Global Cache (Mars Data + Manual Map) -> CHT
    2. Official TWSE/TPEx APIs -> CHT (New)
    3. YFinance -> Often EN
    """
    stock_id = str(stock_id).strip()
    # Ensure cache is loaded?
    if not STOCK_NAME_CACHE:
        load_stock_name_cache()
    
    # 1. Check Cache
    if stock_id in STOCK_NAME_CACHE:
        return STOCK_NAME_CACHE[stock_id]
        
    # 2. Try Official API (Chinese Name)
    try:
        cht_name = fetch_chinese_name_from_api(stock_id)
        if cht_name:
            STOCK_NAME_CACHE[stock_id] = cht_name
            print(f"[Fetch] Used API for {stock_id}: {cht_name}")
            return cht_name
    except Exception:
        pass

    # 3. YFinance Fallback
    # Try TW then TWO
    for suffix in ['.TW', '.TWO']:
        try:
            ticker = yf.Ticker(f"{stock_id}{suffix}")
            # Try fetching explicit name
            info = ticker.info # This triggers a network request
            
            # YF often gives English 'longName'.
            # We check if there is a 'shortName' which might be better?
            # Usually they are both English for TW stocks in YF.
            name = info.get('longName') or info.get('shortName')
            if name:
                # Cache it (even if English, better than nothing)
                STOCK_NAME_CACHE[stock_id] = name
                return name
        except Exception:
            continue
    return None

def fetch_live_prices(stock_ids: list) -> dict:
    import pandas as pd
    import yfinance as yf
    """
    Fetch live prices for a list of stock IDs.
    Returns: { "2330": { "price": 1000, "change_pct": 2.5, "name": "TSMC" } }
    
    Used by Portfolio Tab for real-time (~30s delayed) price display.
    """
    if not stock_ids:
        return {}
    
    unique_ids = list(set(stock_ids))
    
    # Build YF tickers (try .TW first, then .TWO for OTC)
    yf_tickers = []
    id_map = {}  # YF Ticker -> Input ID
    
    for sid in unique_ids:
        if sid.isdigit():
            # Primary: TWSE (.TW)
            t_tw = f"{sid}.TW"
            yf_tickers.append(t_tw)
            id_map[t_tw] = sid
            # Fallback: TPEx (.TWO) for OTC stocks
            t_two = f"{sid}.TWO"
            yf_tickers.append(t_two)
            id_map[t_two] = sid
        elif '.' in sid:
            # Already has suffix
            yf_tickers.append(sid)
            id_map[sid] = sid.split('.')[0]
        else:
            t = f"{sid}.TW"
            yf_tickers.append(t)
            id_map[t] = sid
                
    if not yf_tickers:
        return {}
    
    result = {}
    try:
        # Download 2 days to calculate change_pct
        data = yf.download(yf_tickers, period="2d", progress=False)
        
        if data.empty:
            return {}
        
        close_data = data['Close']
        
        # Handle single vs multi ticker
        if isinstance(close_data, pd.Series):
            # Single ticker case
            if len(close_data) >= 2:
                prev_close = close_data.iloc[-2]
                curr_close = close_data.iloc[-1]
                if pd.notna(curr_close) and pd.notna(prev_close) and prev_close != 0:
                    change_pct = ((curr_close - prev_close) / prev_close) * 100
                    sid = id_map.get(yf_tickers[0], yf_tickers[0])
                    result[sid] = {"price": round(float(curr_close), 2), "change_pct": round(change_pct, 2)}
            elif len(close_data) == 1:
                curr_close = close_data.iloc[-1]
                if pd.notna(curr_close):
                    sid = id_map.get(yf_tickers[0], yf_tickers[0])
                    result[sid] = {"price": round(float(curr_close), 2), "change_pct": 0.0}
        else:
            # Multi ticker DataFrame
            for tick in yf_tickers:
                if tick not in close_data.columns:
                    continue
                    
                sid = id_map.get(tick, tick)
                if sid in result:
                    continue  # Skip if already found via .TW
                    
                col = close_data[tick].dropna()
                if len(col) >= 2:
                    prev_close = col.iloc[-2]
                    curr_close = col.iloc[-1]
                    if prev_close != 0:
                        change_pct = ((curr_close - prev_close) / prev_close) * 100
                        result[sid] = {"price": round(float(curr_close), 2), "change_pct": round(change_pct, 2)}
                elif len(col) == 1:
                    curr_close = col.iloc[-1]
                    result[sid] = {"price": round(float(curr_close), 2), "change_pct": 0.0}
                            
    except Exception as e:
        print(f"[Price Fetch] Batch Error: {e}")
        
    return result

def update_price_cache(stock_id: str):
    import pandas as pd
    import yfinance as yf
    """
    Fetch monthly historical data for a stock and update cache.
    Optimized to only fetch if no data exists.
    Returns the ACTUAL stock_id used in cache (e.g. '00937B.TWO') or None if failed.
    """
    with get_db() as conn:
        cursor = conn.cursor()
        
        # 1. Check Exact Match (Valid Data or Error Marker)
        cursor.execute("SELECT month FROM race_cache WHERE stock_id = ? LIMIT 1", (stock_id,))
        row = cursor.fetchone()
        if row:
            if row[0] == 'ERROR':
                return None # Negative Cache Hit
            return stock_id
            
        # 2. Check Alternates in DB
        alternates = []
        if stock_id.endswith('.TW'):
            alternates.append(stock_id.replace('.TW', '.TWO'))
        elif stock_id.endswith('.TWO'):
            alternates.append(stock_id.replace('.TWO', '.TW'))
        else:
            alternates.append(f"{stock_id}.TW")
            alternates.append(f"{stock_id}.TWO")
            
        for alt in alternates:
            cursor.execute("SELECT month FROM race_cache WHERE stock_id = ? LIMIT 1", (alt,))
            row = cursor.fetchone()
            if row:
                if row[0] == 'ERROR':
                     continue
                # print(f"[Race Cache] Found alternate in DB: {alt}")
                return alt

    # 3. Fetch from YFinance (if not in DB)
    try:
        # Helper to fetch
        def try_fetch(sid):
            try:
                t = yf.Ticker(sid)
                h = t.history(period="max", interval="1mo")
                return h
            except Exception as e:
                print(f"[Race Cache] YF Fetch Error for {sid}: {e}")
                import pandas as pd
                return pd.DataFrame()

        hist = try_fetch(stock_id)
        
        # If empty, try alternate suffixes for TW/TWO
        final_id = stock_id
        if hist.empty:
            alt_id = None
            if stock_id.endswith('.TW'):
                alt_id = stock_id.replace('.TW', '.TWO')
            elif stock_id.endswith('.TWO'):
                 alt_id = stock_id.replace('.TWO', '.TW')
            
            if alt_id:
                print(f"[Race Cache] {stock_id} empty. Trying alternate: {alt_id}")
                hist_alt = try_fetch(alt_id)
                if not hist_alt.empty:
                    hist = hist_alt
                    final_id = alt_id
        
        if hist.empty:
            print(f"[Race Cache] No data found for {stock_id} (or alternates). CACHING FAILURE.")
            with get_db() as conn:
                conn.execute("INSERT OR REPLACE INTO race_cache (stock_id, month, close_price) VALUES (?, 'ERROR', 0)", (stock_id,))
            return None

        # Insert Data
        data_to_insert = []
        for date, row in hist.iterrows():
            month_str = date.strftime('%Y-%m')
            close = row['Close']
            if pd.notna(close):
                data_to_insert.append((final_id, month_str, float(close)))

        with get_db() as conn:
            cursor = conn.cursor()
            cursor.executemany("""
                INSERT OR REPLACE INTO race_cache (stock_id, month, close_price)
                VALUES (?, ?, ?)
            """, data_to_insert)
            
        print(f"[Race Cache] Updated {final_id} ({len(data_to_insert)} rows)")
        return final_id
            
    except Exception as e:
        print(f"[Race Cache] Error updating {stock_id}: {e}")
        try:
            with get_db() as conn:
                conn.execute("INSERT OR REPLACE INTO race_cache (stock_id, month, close_price) VALUES (?, 'ERROR', 0)", (stock_id,))
        except Exception:
            pass
        return None

def ensure_price_cache_batch(stock_ids: list, start_date: str = None) -> dict:
    """
    Batch update price cache for multiple stock IDs.
    Returns a dict mapping {input_id: valid_yf_id}
    """
    import pandas as pd
    import yfinance as yf
    if not stock_ids:
        return {}
    
    unique_ids = list(set(stock_ids))
    mapping = {sid: sid for sid in unique_ids} # Default map
    
    # 1. Filter out IDs that already exist in DB
    missing_ids = []
    with get_db() as conn:
        placeholders = ','.join(['?'] * len(unique_ids))
        cursor = conn.cursor()
        cursor.execute(f"SELECT DISTINCT stock_id FROM race_cache WHERE stock_id IN ({placeholders})", unique_ids)
        existing = set(row[0] for row in cursor.fetchall())
        
        for sid in unique_ids:
            if sid not in existing:
                missing_ids.append(sid)

    # 3. Batch Fetch Missing
    real_missing = missing_ids
    if not real_missing:
        return mapping
        
    # We will process `real_missing` in 2 rounds.
    # Round 1: Try .TW (or default)
    # Prepare batch 1 tickers
    batch1_map = {} # ticker -> original_id
    for sid in real_missing:
        if sid.endswith('.TW') or sid.endswith('.TWO'):
            ticker = sid
        elif len(sid) == 4 and sid.isdigit():
             ticker = f"{sid}.TW"
        else: # ETFs etc
             ticker = f"{sid}.TW" # Try TW first
        batch1_map[ticker] = sid
        
    all_tickers1 = list(batch1_map.keys())
    CHUNK_SIZE = 5
    
    # Pre-filter Bad Tickers
    valid_missing = []
    bad_tickers = []
    for sid in real_missing:
        if len(sid) == 5 and sid.isdigit(): # e.g. 65331 check
             bad_tickers.append(sid)
        else:
             valid_missing.append(sid)
             
    if bad_tickers:
        with get_db() as conn:
             conn.executemany("INSERT OR REPLACE INTO race_cache (stock_id, month, close_price) VALUES (?, 'ERROR', 0)", [(fid,) for fid in bad_tickers])
             
    # Prepare batch 1 tickers (filtered)
    batch1_map = {} 
    for sid in valid_missing:
        if sid.endswith('.TW') or sid.endswith('.TWO'):
            ticker = sid
        elif len(sid) == 4 and sid.isdigit():
             ticker = f"{sid}.TW"
        else:
             ticker = f"{sid}.TW"
        batch1_map[ticker] = sid
        
    all_tickers1 = list(batch1_map.keys())
    successful_orig_ids = set()

    if all_tickers1:
        for i in range(0, len(all_tickers1), CHUNK_SIZE):
            chunk_tickers = all_tickers1[i:i+CHUNK_SIZE]
            try:
                if start_date:
                    data1 = yf.download(chunk_tickers, start=start_date, interval="1mo", progress=False, threads=False)['Close']
                else:
                    data1 = yf.download(chunk_tickers, period="10y", interval="1mo", progress=False, threads=False)['Close']
                
                if len(chunk_tickers) == 1:
                    if isinstance(data1, pd.Series):
                        data1 = data1.to_frame(name=chunk_tickers[0])
                
                to_insert = []
                if not data1.empty:
                    for col_ticker in data1.columns:
                        series = data1[col_ticker]
                        if series.dropna().empty:
                            continue 
                        
                        original_id = batch1_map.get(col_ticker, col_ticker)
                        mapping[original_id] = col_ticker
                        successful_orig_ids.add(original_id) 
                        
                        for date, price in series.items():
                            if pd.notna(price):
                                to_insert.append((col_ticker, date.strftime('%Y-%m'), float(price)))
                
                if to_insert:
                    with get_db() as conn:
                        conn.executemany("INSERT OR REPLACE INTO race_cache (stock_id, month, close_price) VALUES (?, ?, ?)", to_insert)
                
                del data1, to_insert
                gc.collect()
            except Exception as e:
                print(f"[Race Batch] Chunk Error: {e}")
                
    # Round 2: Alternates
    leftovers = [id for id in valid_missing if id not in successful_orig_ids]
    if leftovers:
        batch2_map = {}
        for sid in leftovers:
            if sid.endswith('.TWO'):
                ticker = sid.replace('.TWO', '.TW')
            elif sid.endswith('.TW'):
                ticker = sid.replace('.TW', '.TWO')
            elif len(sid) == 4 and sid.isdigit():
                ticker = f"{sid}.TWO"  # If default TW failed, try TWO
            else:
                ticker = f"{sid}.TWO"  # If default TW array failed, try fallback
            batch2_map[ticker] = sid
        
        all_tickers2 = list(batch2_map.keys())
        successful_orig_ids_2 = set()
        
        for i in range(0, len(all_tickers2), CHUNK_SIZE):
            chunk_tickers = all_tickers2[i:i+CHUNK_SIZE]
            try:
                if start_date:
                    data2 = yf.download(chunk_tickers, start=start_date, interval="1mo", progress=False, threads=False)['Close']
                else:
                    data2 = yf.download(chunk_tickers, period="10y", interval="1mo", progress=False, threads=False)['Close']

                if len(chunk_tickers) == 1 and isinstance(data2, pd.Series):
                    data2 = data2.to_frame(name=chunk_tickers[0])
                    
                to_insert2 = []
                if not data2.empty:
                    for col_ticker in data2.columns:
                         series = data2[col_ticker]
                         if series.dropna().empty:
                             continue 
                         
                         original_id = batch2_map.get(col_ticker, col_ticker)
                         mapping[original_id] = col_ticker
                         successful_orig_ids_2.add(original_id)
                         
                         for date, price in series.items():
                            if pd.notna(price):
                                to_insert2.append((col_ticker, date.strftime('%Y-%m'), float(price)))
                                
                if to_insert2:
                    with get_db() as conn:
                        conn.executemany("INSERT OR REPLACE INTO race_cache (stock_id, month, close_price) VALUES (?, ?, ?)", to_insert2)
                        
                del data2, to_insert2
                gc.collect()
            
            except Exception as e:
                 print(f"[Race Batch] Round 2 Chunk Error: {e}")

        # Mark Failures
        final_failures = [orig for orig in leftovers if orig not in successful_orig_ids_2]
        if final_failures:
            with get_db() as conn:
                conn.executemany("INSERT OR REPLACE INTO race_cache (stock_id, month, close_price) VALUES (?, 'ERROR', 0)", [(fid,) for fid in final_failures])
    
    return mapping

def get_cached_prices_batch(stock_ids: list, start_date: str = None) -> Dict[str, Any]:
    """
    Fetch monthly prices from SQLite `race_cache` table.
    Returns: { "2330": pd.Series(index=Date, data=Price) }
    """
    import pandas as pd
    if not stock_ids:
        return {}
    
    unique_ids = list(set(stock_ids))
    placeholders = ','.join(['?'] * len(unique_ids))
    
    results = {}
    with get_db() as conn:
        cursor = conn.cursor()
        # Fetch all relevant rows
        # We need to handle alternates? The cache stores by requested stock_id if successful?
        # ensure_price_cache_batch maps input_id to valid_yf_id.
        # But RaceCache stores `stock_id` as the Valid YF ID (mostly).
        # We need to query by stock_id OR aliases. 
        # But since ensure_price_cache_batch returns a mapping, the caller should use that mapping.
        # However, for simplicity here, we just query what we have.
        
        query = f"SELECT stock_id, month, close_price FROM race_cache WHERE stock_id IN ({placeholders})"
        cursor.execute(query, unique_ids)
        rows = cursor.fetchall()
        
    # Convert to Dict of Series
    data_map = {}
    for r in rows:
        sid, month, price = r
        if month == 'ERROR':
            continue 
        if sid not in data_map:
            data_map[sid] = {'dates': [], 'prices': []}
        
        # Month to Date (End of Month?)
        # race_cache stores 'YYYY-MM'.
        # We convert to datetime for Series index.
        dt = datetime.strptime(month + "-01", "%Y-%m-%d") 
        # Ideally EndOfMonth but 1st is fine for monthly index align
        data_map[sid]['dates'].append(dt)
        data_map[sid]['prices'].append(price)
        
    for sid, d in data_map.items():
        if d['dates']:
            s = pd.Series(data=d['prices'], index=d['dates'])
            s = s.sort_index()
            # Filter start_date if needed
            if start_date:
                s = s[s.index >= pd.Timestamp(start_date)]
            results[sid] = s
            
    return results

def fetch_history_series(ticker: str, period: str = "1y") -> Any:
    import yfinance as yf
    """
    Fetch historical data for a ticker.
    Used by NotificationEngine for SMA calculations.
    """
    try:
        # Check if it's a valid ticker format (e.g. 4-6 chars + .TW/.TWO or just digits)
        # Avoid UUIDs or session IDs
        if '-' in ticker or len(ticker) > 20:
             import pandas as pd
             return pd.DataFrame()

        if not (ticker.endswith('.TW') or ticker.endswith('.TWO')):
             # Auto-detect correctly if missing using DB
             try:
                 from app.services.market_db import get_connection
                 conn = get_connection(read_only=True)
                 cat = conn.execute("SELECT market_type FROM stocks WHERE stock_id = ?", (ticker,)).fetchone()
                 if cat and cat[0] == "TPEx":
                     ticker += '.TWO'
                 else:
                     ticker += '.TW'
                 conn.close()
             except Exception:
                 ticker += '.TW'
        
        t = yf.Ticker(ticker)
        return t.history(period=period)
    except Exception as e:
        print(f"[MarketData] Fetch History Error for {ticker}: {e}")
        import pandas as pd
        return pd.DataFrame()

        if not (ticker.endswith('.TW') or ticker.endswith('.TWO')):
             if len(ticker) >= 4 and ticker[:4].isdigit():
                 ticker += '.TW'
        
        t = yf.Ticker(ticker)
        return t.history(period=period)
    except Exception as e:
        print(f"[MarketData] Fetch History Error for {ticker}: {e}")
        import pandas as pd
        return pd.DataFrame()

def fetch_stock_info(ticker: str) -> dict:
    import yfinance as yf
    """
    Fetch stock info (fast_info preferred).
    Returns dict with keys like 'lastPrice', 'marketCap', 'twoHundredDayAverage'.
    """
    try:
        if not (ticker.endswith('.TW') or ticker.endswith('.TWO')):
             try:
                 from app.services.market_db import get_connection
                 conn = get_connection(read_only=True)
                 cat = conn.execute("SELECT market_type FROM stocks WHERE stock_id = ?", (ticker,)).fetchone()
                 if cat and cat[0] == "TPEx":
                     ticker += '.TWO'
                 else:
                     ticker += '.TW'
                 conn.close()
             except Exception:
                 ticker += '.TW'
        
        t = yf.Ticker(ticker)
        fi = t.fast_info
        # Convert to dict to decouple caller from yfinance object
        return {
            'lastPrice': fi.last_price,
            'marketCap': fi.market_cap,
            'twoHundredDayAverage': fi.two_hundred_day_average,
            'yearHigh': fi.year_high,
            'yearLow': fi.year_low
        }
    except Exception as e:
        print(f"[MarketData] Fetch Info Error for {ticker}: {e}")
        return {}

    # return result

# Atomic JSON saving removed in favor of DuckDB

def load_stock_list():
    """Load stock list from CSV."""
    import pandas as pd
    base_dir = Path(__file__).parent.parent # app/
    csv_path = base_dir / "project_tw/stock_list.csv"
    
    if not csv_path.exists():
         csv_path = base_dir.parent / "app/project_tw/stock_list.csv"
         
    if not csv_path.exists():
        # Last resort
        csv_path = Path("/app/app/project_tw/stock_list.csv")
        
    if not csv_path.exists():
        raise FileNotFoundError(f"Stock list not found at {csv_path}")

    return pd.read_csv(csv_path, dtype={'code': str, 'name': str})


def backfill_all_stocks(period: str = "max", overwrite: bool = False, progress_callback: Optional[Callable] = None, include_warrants: Optional[bool] = None, tickers: Optional[List[str]] = None, start_date: Optional[str] = None, end_date: Optional[str] = None, chunk_size: int = 50) -> dict:
    """
    Download historical data for ALL stocks and save to daily_prices.
    Uses chunking to avoid memory issues and rate limits.
    """

    if progress_callback:
        progress_callback("Loading dependencies...", 2)
    import pandas as pd
    import yfinance as yf
    if progress_callback:
        progress_callback("Dependencies loaded. Reading stock list...", 5)
    """
    Backfill historical data for all stocks in the cache.
    Saves to data/raw/Market_{Year}_Prices.json and TPEx_Market_{Year}_Prices.json.
    Also fetches dividend history and saves to TWSE_Dividends_{Year}.json.
    
    Args:
        period: yfinance period (max, 10y, etc)
        overwrite: If False, skip existing ticker/year entries to preserve manual patches.
        progress_callback: Optional function(message, percentage) for real-time tracking.
        include_warrants: If True, includes short-lived warrants (6-digit code, nan industry).
                         If None, uses environment default (True locally, False on cloud).
        tickers: Optional list of stock IDs to filter the backfill.
        start_date: Start date string (YYYY-MM-DD). If provided, overrides period.
        end_date: End date string (YYYY-MM-DD). If provided, overrides period.
    """
    # 1. Load Stock List
    base_dir = Path(__file__).parent.parent # app/
    csv_path = base_dir / "project_tw/stock_list.csv"
    
    if not csv_path.exists():
         csv_path = base_dir.parent / "app/project_tw/stock_list.csv"
         
    if not csv_path.exists():
        return {"status": "error", "message": f"Stock list not found at {csv_path}"}

    print(f"[Backfill] Reading stock list from {csv_path}")
    try:
        df = pd.read_csv(csv_path, dtype={'code': str, 'name': str})
    except Exception as e:
        return {"status": "error", "message": f"Failed to read CSV: {e}"}

    # Detect environment early for warrant filtering and batch tuning
    IS_CLOUD = os.getenv("ZEABUR") or os.getenv("RAILWAY") or os.getenv("RENDER")

    # 2. Prepare Tasks
    tasks = []
    if 'market_type' not in df.columns:
         return {"status": "error", "message": "CSV missing 'market_type' column"}

    for _, row in df.iterrows():
        code = str(row['code']).strip()
        industry = str(row.get('industry', 'nan')).strip()
        mtype = str(row.get('market_type', '')).strip()

        # Validation: Stock codes are usually 4-6 digits, ETFs 5-6 digits.
        # Avoid any UUIDs, session IDs, or long metadata strings.
        if not (code.isdigit() or (len(code) >= 4 and len(code) <= 8)):
             continue
             
        # --- SMART UNIVERSE FILTER (COMPLETENESS vs STABILITY) ---
        # 48,000+ total items include ~45,000 Warrants (6-digits, nan industry).
        # Warrants are short-lived derivatives and NOT needed for core Mars strategy.
        # Removing them ensures stability (2,500 vs 50,000 stocks) without losing completeness.
        
        # Environment default: Include warrants locally, exclude on cloud if not explicitly requested.
        effective_warrant_flag = include_warrants if include_warrants is not None else (not IS_CLOUD)
        
        if not effective_warrant_flag and len(code) == 6 and industry == 'nan':
            continue
             
        
        if tickers and code not in tickers:
            continue
            
        if mtype == 'Listed':
            suffix, market = '.TW', 'TWSE'
        elif mtype == 'OTC':
            suffix, market = '.TWO', 'TPEx'
        else:
            continue
        
        tasks.append((f"{code}{suffix}", market, code))
    
    if not tasks:
        return {"status": "error", "message": "No valid stocks found in CSV"}

    print(f"[Backfill] Found {len(tasks)} stocks to process.")

    print(f"[Backfill] Found {len(tasks)} stocks to process.")
    if progress_callback:
        progress_callback("Initializing backfill...", 5)

    # 4. Batch Processing
    market_map = {t[0]: t[1] for t in tasks}
    original_code_map = {t[0]: t[2] for t in tasks}
    all_tickers = [t[0] for t in tasks]
    
    # --- ADAPTIVE STABILITY TUNING ---
    # Detect environment to balance stability (Tank Mode) vs. performance (Fast Mode)
    
    if IS_CLOUD:
        # TANK MODE: Ultra-stable for 512MB RAM
        # SAVE_INTERVAL = 20 # Redundant, removed
        BATCH_DELAY = 0.5
        print("[Backfill] Adaptive Mode: TANK (Cloud Detected - 512MB Safety)")
    else:
        # FAST MODE: Performance for local dev (8GB+ RAM)
        # SAVE_INTERVAL = 20  # Reduced: 200 stocks × 1000 rows was too large for ON CONFLICT upserts
        BATCH_DELAY = 0
        print("[Backfill] Adaptive Mode: FAST (Local Environment)")
    
    total_tickers = len(all_tickers)
    results = {}     # year -> market -> code -> data
    div_results = {} # year -> code -> data

    import time
    import gc

    def flush_results(results_to_save, div_results_to_save):
        """Helper to save current batch and clear memory."""
        if not results_to_save and not div_results_to_save:
            return
        print("[Backfill] Flushing data to DuckDB...")
        # DEBUG
        # print(f"[DEBUG] Flushing {len(results_to_save)} years. Keys: {results_to_save.keys()}", flush=True)
        
        conn = get_connection()
        try:
            # 1. Save Prices
            price_rows = []
            for year, markets in results_to_save.items():
                for m_name, market_data in markets.items():
                    for code, data in market_data.items():
                        for day in data["daily"]:
                            price_rows.append((
                                code, day["d"], 
                                float(day["o"]), float(day["h"]), 
                                float(day["l"]), float(day["c"]), 
                                int(day["v"]), m_name
                            ))
            
            if price_rows:
                # Use batch size for DuckDB to be safe with memory
                batch_size = 50000
                for j in range(0, len(price_rows), batch_size):
                    batch = price_rows[j:j+batch_size]
                    conn.execute("BEGIN TRANSACTION")
                    conn.executemany("""
                        INSERT INTO daily_prices (stock_id, date, open, high, low, close, volume, market)
                        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                        ON CONFLICT (stock_id, date) DO UPDATE SET
                            open = EXCLUDED.open, high = EXCLUDED.high, low = EXCLUDED.low,
                            close = EXCLUDED.close, volume = EXCLUDED.volume, market = EXCLUDED.market
                    """, batch)
                    conn.execute("COMMIT")
                print(f"[Backfill] Inserted {len(price_rows)} price rows.")

            # 2. Save Dividends
            div_rows = []
            for year, year_divs in div_results_to_save.items():
                for code, div_data in year_divs.items():
                    div_rows.append((code, year, float(div_data['cash']), float(div_data['stock'])))
            
            if div_rows:
                conn.execute("BEGIN TRANSACTION")
                conn.executemany("""
                    INSERT INTO dividends (stock_id, year, cash, stock)
                    VALUES (?, ?, ?, ?)
                    ON CONFLICT (stock_id, year) DO UPDATE SET
                        cash = EXCLUDED.cash, stock = EXCLUDED.stock
                """, div_rows)
                conn.execute("COMMIT")
                print(f"[Backfill] Inserted {len(div_rows)} dividend rows.")

        except Exception as e:
            print(f"[Backfill] DuckDB Save Error: {e}")
            try:
                conn.execute("ROLLBACK")
            except Exception as e:
                pass
        finally:
            conn.close()
            
        results_to_save.clear()
        div_results_to_save.clear()
        gc.collect()



    for i in range(0, total_tickers, chunk_size):
        chunk = all_tickers[i:i+chunk_size]
        print(f"[Backfill] Processing chunk {i//chunk_size + 1}/{(total_tickers-1)//chunk_size + 1}...")
        
        batch = (i // chunk_size) + 1
        
        if progress_callback:
            pct = 10 + int((i / total_tickers) * 80)
            total_batches = (total_tickers + chunk_size - 1) // chunk_size
            first = chunk[0]
            progress_callback(f"Batch {batch}/{total_batches}: Fetching {period} history for {first}...", pct)
        
        try:
            # Download with threads=not IS_CLOUD (works reliably if chunk_size=1)
            run_threads = not IS_CLOUD
            # CRITICAL: auto_adjust=False to get Nominal prices (yfinance defaults to True)
            if start_date:
                data = yf.download(chunk, start=start_date, end=end_date, group_by='ticker', actions=True, auto_adjust=False, progress=False, threads=run_threads)
            else:
                data = yf.download(chunk, period=period, group_by='ticker', actions=True, auto_adjust=False, progress=False, threads=run_threads)
            
            print(f"[Debug] Batch {batch}: Downloaded {len(data)} rows for {chunk}.", flush=True)
            
            if data.empty:
                continue 
            
            for ticker in chunk:
                # Robust extraction for Yfinance 1.0+ which returns MultiIndex even for single ticker
                df_ticker = data
                if isinstance(data.columns, pd.MultiIndex) and ticker in data.columns:
                    df_ticker = data[ticker]
                if df_ticker.empty:
                    continue 
                df_ticker = df_ticker.dropna(how='all')
                if df_ticker.empty:
                    continue 
                
                market = market_map.get(ticker, 'TWSE')
                code = original_code_map.get(ticker, ticker)
                
                # DEBUG
                # print(f"[DEBUG] Processing {ticker}. Rows: {len(df_ticker)}. Index: {type(df_ticker.index)}")

                # 4.1. Process Dividends & Splits
                if 'Dividends' in df_ticker.columns or 'Stock Splits' in df_ticker.columns:
                    actions = df_ticker[(df_ticker.get('Dividends', 0) > 0) | (df_ticker.get('Stock Splits', 0) > 0)]
                    for idx, row in actions.iterrows():
                        y = idx.year
                        if y < 2000:
                            continue 
                        if y not in div_results:
                            div_results[y] = {}
                        if code not in div_results[y]:
                            div_results[y][code] = {'cash': 0.0, 'stock': 0.0}
                        
                        div_val = float(row.get('Dividends', 0))
                        split_val = float(row.get('Stock Splits', 0))
                        
                        if div_val > 0:
                            div_results[y][code]['cash'] += div_val
                        if split_val > 0 and split_val != 1.0:
                            # yfinance Stock Splits: 1.1 ratio means 10% stock div -> 0.1 in our format
                            div_results[y][code]['stock'] += (split_val - 1.0)

                # 4.2. Process Prices with Smart Merge logic
                if not isinstance(df_ticker.index, pd.DatetimeIndex):
                    continue 
                
                df_ticker['Year'] = df_ticker.index.year
                for year, group in df_ticker.groupby('Year'):
                    if year < 2000:
                        continue 
                    daily_data = []
                    for idx, row in group.iterrows():
                        try:
                            o, h, low_val, c, v = row['Open'], row['High'], row['Low'], row['Close'], row['Volume']
                            if pd.isna(c) or (v == 0 and o == 0 and c == 0):
                                continue 
                            daily_data.append({
                                "d": idx.strftime('%Y-%m-%d'), 
                                "o": round(float(o), 2), "h": round(float(h), 2), 
                                "l": round(float(low_val), 2), "c": round(float(c), 2), 
                                "v": int(v)
                            })
                        except Exception as e:
                            # Log but continue
                            print(f"[Error] Processing ticker {ticker}: {e}")
                            continue
                    
                    try:
                        high_val, low_val = max(d['h'] for d in daily_data), min(d['l'] for d in daily_data)
                        summary = {"start": daily_data[0]['o'], "end": daily_data[-1]['c'], "high": high_val, "low": low_val}
                        
                        if year not in results:
                            results[year] = {'TWSE': {}, 'TPEx': {}}
                        results[year][market][code] = {"daily": daily_data, "summary": summary}
                    except Exception:
                        # print(f"[Error] Summary calc error: {e}")
                        pass

                # End of Ticker Loop
            
            # Flush at end of chunk
            flush_results(results, div_results)

        except Exception as e:
            print(f"[Backfill] Chunk Error: {e}")
        
        # Explicit GC to free memory after EVERY batch/stock
        del data
        gc.collect()
        if BATCH_DELAY > 0:
            time.sleep(BATCH_DELAY)

    # 5. Final Flush
    flush_results(results, div_results)
    
    if progress_callback:
        progress_callback("Backfill complete!", 100)
    return {"status": "ok", "stocks_processed": total_tickers}
