
import httpx
import sqlite3
import pandas as pd
import yfinance as yf
import gc
from datetime import datetime, timedelta
from typing import Optional, Dict, List, Any
from pathlib import Path

from app.database import get_db
from app.config import STOCK_NAME_CACHE, SUPPLEMENTARY_NAME_CACHE

def load_stock_name_cache():
    """Load stock names from Mars Strategy Excel file into global cache."""
    # Load from CSV (Generated by StockInfoService)
    try:
        # 1. Try relative to this file (for deployed app)
        base_dir = Path(__file__).parent.parent # app/
        # Try finding the CSV file in standard locations
        csv_path = base_dir / "project_tw/stock_list.csv"
        
        if not csv_path.exists():
            # Dev environment fallback
            csv_path = base_dir.parent / "app/project_tw/stock_list.csv"
            
        if not csv_path.exists():
             # Last resort: Try root
             csv_path = Path("/app/app/project_tw/stock_list.csv")

        if csv_path.exists():
            print(f"[Cache] Loading stock names from {csv_path}")
            # CSV columns: code, name, industry, market_type
            df = pd.read_csv(csv_path, dtype={'code': str, 'name': str})
            
            # Create dict: code -> name
            if 'code' in df.columns and 'name' in df.columns:
                new_cache = dict(zip(df['code'], df['name']))
                STOCK_NAME_CACHE.update(new_cache)
                print(f"[Cache] Loaded {len(new_cache)} stock names")
            else:
                print(f"[Cache Warning] Columns 'code'/'name' not found in {csv_path}")
                
            # Merge Manual Map
            STOCK_NAME_CACHE.update(SUPPLEMENTARY_NAME_CACHE)
        else:
             print(f"[Cache Warning] Stock list CSV not found at {csv_path}")
             
    except Exception as e:
        print(f"[Cache Error] Failed to load stock list CSV: {e}")

    # Merge Supplementary Cache (Overrides Excel if collision, or adds new) - Already done above
    if SUPPLEMENTARY_NAME_CACHE:
        # print(f"[Cache] Merging {len(SUPPLEMENTARY_NAME_CACHE)} supplementary names")
        STOCK_NAME_CACHE.update(SUPPLEMENTARY_NAME_CACHE)

def fetch_chinese_name_from_api(stock_id: str) -> Optional[str]:
    """
    Fetch Chinese name from TWSE/TPEx official APIs.
    Fallback logic for missing names.
    """
    try:
        today = datetime.now()
        # TWSE/TPEx data usually available after 1:30 PM.
        # but usually using a known recent date or just 'latest' if API supports
        # TWSE needs specific date. Let's use yesterday.
        offset = 1
        if today.weekday() == 0: offset = 3 # Monday -> Friday
        elif today.weekday() == 6: offset = 2 # Sunday -> Friday
        
        date_obj = today - timedelta(days=offset)
        date_str = date_obj.strftime("%Y%m%d")
        
        # Try TWSE first (covers most stocks)
        try:
            url = "https://www.twse.com.tw/exchangeReport/MI_INDEX"
            params = {"response": "json", "type": "ALLBUT0999", "date": date_str}
            
            # fast timeout
            with httpx.Client(verify=False, timeout=5.0) as client:
                resp = client.get(url, params=params)
                data = resp.json()
                
                if data.get('stat') == 'OK':
                    tables = data.get('tables', [])
                    # Usually table 9 is the main price table with Code/Name
                    for table in tables:
                        fields = table.get('fields', [])
                        if '證券代號' in fields and '證券名稱' in fields:
                            idx_code = fields.index('證券代號')
                            idx_name = fields.index('證券名稱')
                            
                            for row in table.get('data', []):
                                if row[idx_code] == stock_id:
                                    return row[idx_name]
        except Exception as e:
            print(f"[API] TWSE fetch error: {e}")
        
        # Try TPEx (OTC stocks)
        try:
            # TPEx needs ROC year: 2024 -> 113
            roc_year = date_obj.year - 1911
            roc_date = f"{roc_year}/{date_obj.month:02d}/{date_obj.day:02d}"
            
            url = "https://www.tpex.org.tw/web/stock/aftertrading/daily_close_quotes/stk_quote_result.php"
            params = {"l": "zh-tw", "d": roc_date, "se": "AL"}  # AL = All securities
            
            with httpx.Client(timeout=5.0) as client:
                resp = client.get(url, params=params)
                data = resp.json()
                
                if 'aaData' in data:
                    for row in data['aaData']:
                        # Row format: [Code, Name, ...]
                        if row[0] == stock_id:
                            return row[1]
        except Exception as e:
            print(f"[API] TPEx fetch error: {e}")
            
    except Exception as e:
        print(f"[API] Error fetching name for {stock_id}: {e}")
    
    return None

def fetch_stock_name(stock_id: str) -> Optional[str]:
    """
    Fetch stock name.
    Priority:
    1. Global Cache (Mars Data + Manual Map) -> CHT
    2. Official TWSE/TPEx APIs -> CHT (New)
    3. YFinance -> Often EN
    """
    stock_id = str(stock_id).strip()
    # Ensure cache is loaded?
    if not STOCK_NAME_CACHE:
        load_stock_name_cache()
    
    # 1. Check Cache
    if stock_id in STOCK_NAME_CACHE:
        return STOCK_NAME_CACHE[stock_id]
        
    # 2. Try Official API (Chinese Name)
    try:
        cht_name = fetch_chinese_name_from_api(stock_id)
        if cht_name:
            STOCK_NAME_CACHE[stock_id] = cht_name
            print(f"[Fetch] Used API for {stock_id}: {cht_name}")
            return cht_name
    except:
        pass

    # 3. YFinance Fallback
    # Try TW then TWO
    for suffix in ['.TW', '.TWO']:
        try:
            ticker = yf.Ticker(f"{stock_id}{suffix}")
            # Try fetching explicit name
            info = ticker.info # This triggers a network request
            
            # YF often gives English 'longName'.
            # We check if there is a 'shortName' which might be better?
            # Usually they are both English for TW stocks in YF.
            name = info.get('longName') or info.get('shortName')
            if name:
                # Cache it (even if English, better than nothing)
                STOCK_NAME_CACHE[stock_id] = name
                return name
        except Exception:
            continue
    return None

def fetch_live_prices(stock_ids: list) -> dict:
    """
    Fetch live prices for a list of stock IDs.
    Returns: { "2330": { "price": 1000, "change_pct": 2.5, "name": "TSMC" } }
    
    Used by Portfolio Tab for real-time (~30s delayed) price display.
    """
    if not stock_ids: return {}
    
    unique_ids = list(set(stock_ids))
    
    # Build YF tickers (try .TW first, then .TWO for OTC)
    yf_tickers = []
    id_map = {}  # YF Ticker -> Input ID
    
    for sid in unique_ids:
        if sid.isdigit():
            # Primary: TWSE (.TW)
            t_tw = f"{sid}.TW"
            yf_tickers.append(t_tw)
            id_map[t_tw] = sid
            # Fallback: TPEx (.TWO) for OTC stocks
            t_two = f"{sid}.TWO"
            yf_tickers.append(t_two)
            id_map[t_two] = sid
        elif '.' in sid:
            # Already has suffix
            yf_tickers.append(sid)
            id_map[sid] = sid.split('.')[0]
        else:
            t = f"{sid}.TW"
            yf_tickers.append(t)
            id_map[t] = sid
                
    if not yf_tickers: return {}
    
    result = {}
    try:
        # Download 2 days to calculate change_pct
        data = yf.download(yf_tickers, period="2d", progress=False)
        
        if data.empty:
            return {}
        
        close_data = data['Close']
        
        # Handle single vs multi ticker
        if isinstance(close_data, pd.Series):
            # Single ticker case
            if len(close_data) >= 2:
                prev_close = close_data.iloc[-2]
                curr_close = close_data.iloc[-1]
                if pd.notna(curr_close) and pd.notna(prev_close) and prev_close != 0:
                    change_pct = ((curr_close - prev_close) / prev_close) * 100
                    sid = id_map.get(yf_tickers[0], yf_tickers[0])
                    result[sid] = {"price": round(float(curr_close), 2), "change_pct": round(change_pct, 2)}
            elif len(close_data) == 1:
                curr_close = close_data.iloc[-1]
                if pd.notna(curr_close):
                    sid = id_map.get(yf_tickers[0], yf_tickers[0])
                    result[sid] = {"price": round(float(curr_close), 2), "change_pct": 0.0}
        else:
            # Multi ticker DataFrame
            for tick in yf_tickers:
                if tick not in close_data.columns:
                    continue
                    
                sid = id_map.get(tick, tick)
                if sid in result:
                    continue  # Skip if already found via .TW
                    
                col = close_data[tick].dropna()
                if len(col) >= 2:
                    prev_close = col.iloc[-2]
                    curr_close = col.iloc[-1]
                    if prev_close != 0:
                        change_pct = ((curr_close - prev_close) / prev_close) * 100
                        result[sid] = {"price": round(float(curr_close), 2), "change_pct": round(change_pct, 2)}
                elif len(col) == 1:
                    curr_close = col.iloc[-1]
                    result[sid] = {"price": round(float(curr_close), 2), "change_pct": 0.0}
                            
    except Exception as e:
        print(f"[Price Fetch] Batch Error: {e}")
        
    return result

def update_price_cache(stock_id: str):
    """
    Fetch monthly historical data for a stock and update cache.
    Optimized to only fetch if no data exists.
    Returns the ACTUAL stock_id used in cache (e.g. '00937B.TWO') or None if failed.
    """
    with get_db() as conn:
        cursor = conn.cursor()
        
        # 1. Check Exact Match (Valid Data or Error Marker)
        cursor.execute("SELECT month FROM race_cache WHERE stock_id = ? LIMIT 1", (stock_id,))
        row = cursor.fetchone()
        if row:
            if row[0] == 'ERROR':
                return None # Negative Cache Hit
            return stock_id
            
        # 2. Check Alternates in DB
        alternates = []
        if stock_id.endswith('.TW'): alternates.append(stock_id.replace('.TW', '.TWO'))
        elif stock_id.endswith('.TWO'): alternates.append(stock_id.replace('.TWO', '.TW'))
        else:
            alternates.append(f"{stock_id}.TW")
            alternates.append(f"{stock_id}.TWO")
            
        for alt in alternates:
            cursor.execute("SELECT month FROM race_cache WHERE stock_id = ? LIMIT 1", (alt,))
            row = cursor.fetchone()
            if row:
                if row[0] == 'ERROR':
                     continue 
                # print(f"[Race Cache] Found alternate in DB: {alt}")
                return alt

    # 3. Fetch from YFinance (if not in DB)
    try:
        # Helper to fetch
        def try_fetch(sid):
            try:
                t = yf.Ticker(sid)
                h = t.history(period="max", interval="1mo")
                return h
            except Exception as e:
                print(f"[Race Cache] YF Fetch Error for {sid}: {e}")
                return pd.DataFrame()

        hist = try_fetch(stock_id)
        
        # If empty, try alternate suffixes for TW/TWO
        final_id = stock_id
        if hist.empty:
            alt_id = None
            if stock_id.endswith('.TW'):
                alt_id = stock_id.replace('.TW', '.TWO')
            elif stock_id.endswith('.TWO'):
                 alt_id = stock_id.replace('.TWO', '.TW')
            
            if alt_id:
                print(f"[Race Cache] {stock_id} empty. Trying alternate: {alt_id}")
                hist_alt = try_fetch(alt_id)
                if not hist_alt.empty:
                    hist = hist_alt
                    final_id = alt_id
        
        if hist.empty:
            print(f"[Race Cache] No data found for {stock_id} (or alternates). CACHING FAILURE.")
            with get_db() as conn:
                conn.execute("INSERT OR REPLACE INTO race_cache (stock_id, month, close_price) VALUES (?, 'ERROR', 0)", (stock_id,))
            return None

        # Insert Data
        data_to_insert = []
        for date, row in hist.iterrows():
            month_str = date.strftime('%Y-%m')
            close = row['Close']
            if pd.notna(close):
                data_to_insert.append((final_id, month_str, float(close)))

        with get_db() as conn:
            cursor = conn.cursor()
            cursor.executemany("""
                INSERT OR REPLACE INTO race_cache (stock_id, month, close_price)
                VALUES (?, ?, ?)
            """, data_to_insert)
            
        print(f"[Race Cache] Updated {final_id} ({len(data_to_insert)} rows)")
        return final_id
            
    except Exception as e:
        print(f"[Race Cache] Error updating {stock_id}: {e}")
        try:
            with get_db() as conn:
                conn.execute("INSERT OR REPLACE INTO race_cache (stock_id, month, close_price) VALUES (?, 'ERROR', 0)", (stock_id,))
        except: pass
        return None

def ensure_price_cache_batch(stock_ids: list, start_date: str = None) -> dict:
    """
    Batch update price cache for multiple stock IDs.
    Returns a dict mapping {input_id: valid_yf_id}
    """
    if not stock_ids: return {}
    
    unique_ids = list(set(stock_ids))
    mapping = {sid: sid for sid in unique_ids} # Default map
    
    # 1. Filter out IDs that already exist in DB
    missing_ids = []
    with get_db() as conn:
        placeholders = ','.join(['?'] * len(unique_ids))
        cursor = conn.cursor()
        cursor.execute(f"SELECT DISTINCT stock_id FROM race_cache WHERE stock_id IN ({placeholders})", unique_ids)
        existing = set(row[0] for row in cursor.fetchall())
        
        for sid in unique_ids:
            if sid not in existing:
                missing_ids.append(sid)

    # 3. Batch Fetch Missing
    real_missing = missing_ids
    if not real_missing:
        return mapping
        
    # We will process `real_missing` in 2 rounds.
    # Round 1: Try .TW (or default)
    # Prepare batch 1 tickers
    batch1_map = {} # ticker -> original_id
    for sid in real_missing:
        if sid.endswith('.TW') or sid.endswith('.TWO'):
            ticker = sid
        elif len(sid) == 4 and sid.isdigit():
             ticker = f"{sid}.TW"
        else: # ETFs etc
             ticker = f"{sid}.TW" # Try TW first
        batch1_map[ticker] = sid
        
    all_tickers1 = list(batch1_map.keys())
    CHUNK_SIZE = 5
    
    # Pre-filter Bad Tickers
    valid_missing = []
    bad_tickers = []
    for sid in real_missing:
        if len(sid) == 5 and sid.isdigit(): # e.g. 65331 check
             bad_tickers.append(sid)
        else:
             valid_missing.append(sid)
             
    if bad_tickers:
        with get_db() as conn:
             conn.executemany("INSERT OR REPLACE INTO race_cache (stock_id, month, close_price) VALUES (?, 'ERROR', 0)", [(fid,) for fid in bad_tickers])
             
    # Prepare batch 1 tickers (filtered)
    batch1_map = {} 
    for sid in valid_missing:
        if sid.endswith('.TW') or sid.endswith('.TWO'):
            ticker = sid
        elif len(sid) == 4 and sid.isdigit():
             ticker = f"{sid}.TW"
        else:
             ticker = f"{sid}.TW"
        batch1_map[ticker] = sid
        
    all_tickers1 = list(batch1_map.keys())
    successful_orig_ids = set()

    if all_tickers1:
        for i in range(0, len(all_tickers1), CHUNK_SIZE):
            chunk_tickers = all_tickers1[i:i+CHUNK_SIZE]
            try:
                if start_date:
                    data1 = yf.download(chunk_tickers, start=start_date, interval="1mo", progress=False, threads=False)['Close']
                else:
                    data1 = yf.download(chunk_tickers, period="10y", interval="1mo", progress=False, threads=False)['Close']
                
                if len(chunk_tickers) == 1:
                    if isinstance(data1, pd.Series):
                        data1 = data1.to_frame(name=chunk_tickers[0])
                
                to_insert = []
                if not data1.empty:
                    for col_ticker in data1.columns:
                        series = data1[col_ticker]
                        if series.dropna().empty: continue
                        
                        original_id = batch1_map.get(col_ticker, col_ticker)
                        mapping[original_id] = col_ticker
                        successful_orig_ids.add(original_id) 
                        
                        for date, price in series.items():
                            if pd.notna(price):
                                to_insert.append((col_ticker, date.strftime('%Y-%m'), float(price)))
                
                if to_insert:
                    with get_db() as conn:
                        conn.executemany("INSERT OR REPLACE INTO race_cache (stock_id, month, close_price) VALUES (?, ?, ?)", to_insert)
                
                del data1, to_insert
                gc.collect()
            except Exception as e:
                print(f"[Race Batch] Chunk Error: {e}")
                
    # Round 2: Alternates
    leftovers = [id for id in valid_missing if id not in successful_orig_ids]
    if leftovers:
        batch2_map = {}
        for sid in leftovers:
            base = sid.replace('.TW', '').replace('.TWO', '')
            ticker = f"{base}.TWO"
            batch2_map[ticker] = sid
        
        all_tickers2 = list(batch2_map.keys())
        successful_orig_ids_2 = set()
        
        for i in range(0, len(all_tickers2), CHUNK_SIZE):
            chunk_tickers = all_tickers2[i:i+CHUNK_SIZE]
            try:
                if start_date:
                    data2 = yf.download(chunk_tickers, start=start_date, interval="1mo", progress=False, threads=False)['Close']
                else:
                    data2 = yf.download(chunk_tickers, period="10y", interval="1mo", progress=False, threads=False)['Close']

                if len(chunk_tickers) == 1 and isinstance(data2, pd.Series):
                    data2 = data2.to_frame(name=chunk_tickers[0])
                    
                to_insert2 = []
                if not data2.empty:
                    for col_ticker in data2.columns:
                         series = data2[col_ticker]
                         if series.dropna().empty: continue
                         
                         original_id = batch2_map.get(col_ticker, col_ticker)
                         mapping[original_id] = col_ticker
                         successful_orig_ids_2.add(original_id)
                         
                         for date, price in series.items():
                            if pd.notna(price):
                                to_insert2.append((col_ticker, date.strftime('%Y-%m'), float(price)))
                                
                if to_insert2:
                    with get_db() as conn:
                        conn.executemany("INSERT OR REPLACE INTO race_cache (stock_id, month, close_price) VALUES (?, ?, ?)", to_insert2)
                        
                del data2, to_insert2
                gc.collect()
            
            except Exception as e:
                 print(f"[Race Batch] Round 2 Chunk Error: {e}")

        # Mark Failures
        final_failures = [orig for orig in leftovers if orig not in successful_orig_ids_2]
        if final_failures:
            with get_db() as conn:
                conn.executemany("INSERT OR REPLACE INTO race_cache (stock_id, month, close_price) VALUES (?, 'ERROR', 0)", [(fid,) for fid in final_failures])
    
    return mapping

def get_cached_prices_batch(stock_ids: list, start_date: str = None) -> Dict[str, pd.Series]:
    """
    Fetch monthly prices from SQLite `race_cache` table.
    Returns: { "2330": pd.Series(index=Date, data=Price) }
    """
    if not stock_ids: return {}
    
    unique_ids = list(set(stock_ids))
    placeholders = ','.join(['?'] * len(unique_ids))
    
    results = {}
    with get_db() as conn:
        cursor = conn.cursor()
        # Fetch all relevant rows
        # We need to handle alternates? The cache stores by requested stock_id if successful?
        # ensure_price_cache_batch maps input_id to valid_yf_id.
        # But RaceCache stores `stock_id` as the Valid YF ID (mostly).
        # We need to query by stock_id OR aliases. 
        # But since ensure_price_cache_batch returns a mapping, the caller should use that mapping.
        # However, for simplicity here, we just query what we have.
        
        query = f"SELECT stock_id, month, close_price FROM race_cache WHERE stock_id IN ({placeholders})"
        cursor.execute(query, unique_ids)
        rows = cursor.fetchall()
        
    # Convert to Dict of Series
    data_map = {}
    for r in rows:
        sid, month, price = r
        if month == 'ERROR': continue
        if sid not in data_map: data_map[sid] = {'dates': [], 'prices': []}
        
        # Month to Date (End of Month?)
        # race_cache stores 'YYYY-MM'.
        # We convert to datetime for Series index.
        dt = datetime.strptime(month + "-01", "%Y-%m-%d") 
        # Ideally EndOfMonth but 1st is fine for monthly index align
        data_map[sid]['dates'].append(dt)
        data_map[sid]['prices'].append(price)
        
    for sid, d in data_map.items():
        if d['dates']:
            s = pd.Series(data=d['prices'], index=d['dates'])
            s = s.sort_index()
            # Filter start_date if needed
            if start_date:
                s = s[s.index >= pd.Timestamp(start_date)]
            results[sid] = s
            
    return results

def fetch_history_series(ticker: str, period: str = "1y") -> pd.DataFrame:
    """
    Fetch historical data for a ticker.
    Used by NotificationEngine for SMA calculations.
    """
    try:
        if not (ticker.endswith('.TW') or ticker.endswith('.TWO')):
             if len(ticker) == 4 and ticker.isdigit(): ticker += '.TW'
        
        t = yf.Ticker(ticker)
        return t.history(period=period)
    except Exception as e:
        print(f"[MarketData] Fetch History Error for {ticker}: {e}")
        return pd.DataFrame()

def fetch_stock_info(ticker: str) -> dict:
    """
    Fetch stock info (fast_info preferred).
    Returns dict with keys like 'lastPrice', 'marketCap', 'twoHundredDayAverage'.
    """
    try:
        if not (ticker.endswith('.TW') or ticker.endswith('.TWO')):
             if len(ticker) == 4 and ticker.isdigit(): ticker += '.TW'
        
        t = yf.Ticker(ticker)
        fi = t.fast_info
        # Convert to dict to decouple caller from yfinance object
        return {
            'lastPrice': fi.last_price,
            'marketCap': fi.market_cap,
            'twoHundredDayAverage': fi.two_hundred_day_average,
            'yearHigh': fi.year_high,
            'yearLow': fi.year_low
        }
    except Exception as e:
        print(f"[MarketData] Fetch Info Error for {ticker}: {e}")
        return {}
