import pytest
import pandas as pd
import os

OUTPUT_PATH = "project_tw/output/stock_list_s2006e2025_unfiltered.xlsx"

def test_output_file_exists():
    if not os.path.exists(OUTPUT_PATH):
        pytest.skip(f"Output file not found: {OUTPUT_PATH}. Run crawler first.")
    assert os.path.exists(OUTPUT_PATH)

def test_specific_stocks_present():
    if not os.path.exists(OUTPUT_PATH):
        pytest.skip("Output file missing")
        
    df = pd.read_excel(OUTPUT_PATH)
    
    # Expanded List (14 items)
    target_list = [
        '00937B', '00953B', '00933B', '00950B', '00945B', 
        '00980D', '00894', '00981A', '00983A', '00830', 
        '009811', '00927', '00878', '00919'
    ]
    
    if 'id' not in df.columns:
        pytest.fail("Column 'id' missing from output dataframe")
        
    # Normalize to string
    df['id'] = df['id'].astype(str)
    existing_ids = set(df['id'].values)
    
    missing = []
    for t in target_list:
        if t not in existing_ids:
            missing.append(t)
            
    # We assert that we found everything, or at least fail with a useful message
    # Note: If this file is generated by a crawler that might be incomplete, 
    # this test will fail, which is good -> it verifies the output.
    assert not missing, f"Missing target stocks in output: {missing}"
