description = "Flow to update the formal product-leve document"
prompt = """
Formal product-releted document location: ./product or ./

## [SPEC] owns
Please prepare/update tinied-up SPEC files formally as following files :
- ./product/specification.md
- ./product/backup_restore.md
- ./product/crawler_architecture.md
- ./product/data_pipeline.md

## [PM] owns
Please prepare/update tinied-up product datasheet and README for the end-users who use the APP (not ME/Terran/BOSS/Agents) as following files
- ./product/datasheet.md
- ./product/README.md, audiences are end-users who use the APP (not ME/Terran/BOSS/Agents)
- ./README.md, audiences are users who watch project or repository, located at GitHub

## [PL][CODE][UI] own
Please prepare/update tinied-up software-perpsective document, the software_stack.
- ./product/software_stack.md

[CV] Please prepare/update tinied-up formal test plan, including automated browser testing flow using related MCP servers as following files
- ./product/test_plan.md
"""
