description = "Create project plan, reiview the plan and generate Ralph loop PRD"
prompt = """
# /ralph_plan - Project Planning Mode with a long-series/comprehensive coverage <br>
No code writing - only plan file generation.

$ARGUMENTS

---
Do strictly follow the following Steps:
1. Use skill `brainstorming` to conceive how/what to achieve $ARGUMENTS
2. Use skill `writing-plans` to plan $ARGUMENTS according to previous brainstorming result
3. `MUST` Write down current plan at `./docs/plan`
4. Use skill `multi-agent-brainstorming` to review preciously created plan
5. `MUST` Write down current plan-review at `./docs/plan`
6. Use skill `ralph_loop_prd` to transform the plan considering plan-review into {plan}_PRD.md for Ralph Loop
7. `MIST` Write down the {plan}_PRD.md at `./docs/plan`
"""
